// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1CrEFyq9VWdgREHMofeoV7UiTivAj54k',
    appId: '1:525851181762:web:1cb4f60451b9888d92f15b',
    messagingSenderId: '525851181762',
    projectId: 'referal-5ee79',
    authDomain: 'referal-5ee79.firebaseapp.com',
    storageBucket: 'referal-5ee79.appspot.com',
    measurementId: 'G-GT3NMM6M70',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALstUhwkXrCJHtRtjUbETCuC62lKPgo1Y',
    appId: '1:525851181762:android:f01185b30a41dfd292f15b',
    messagingSenderId: '525851181762',
    projectId: 'referal-5ee79',
    storageBucket: 'referal-5ee79.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZWwg5m15ahFKh0-IPbQgHlAGwZPCE730',
    appId: '1:525851181762:ios:0d755b5663a287b692f15b',
    messagingSenderId: '525851181762',
    projectId: 'referal-5ee79',
    storageBucket: 'referal-5ee79.appspot.com',
    iosBundleId: 'com.example.referal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZWwg5m15ahFKh0-IPbQgHlAGwZPCE730',
    appId: '1:525851181762:ios:0d755b5663a287b692f15b',
    messagingSenderId: '525851181762',
    projectId: 'referal-5ee79',
    storageBucket: 'referal-5ee79.appspot.com',
    iosBundleId: 'com.example.referal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1CrEFyq9VWdgREHMofeoV7UiTivAj54k',
    appId: '1:525851181762:web:3af01010e3a68e8f92f15b',
    messagingSenderId: '525851181762',
    projectId: 'referal-5ee79',
    authDomain: 'referal-5ee79.firebaseapp.com',
    storageBucket: 'referal-5ee79.appspot.com',
    measurementId: 'G-VY36HFCVQH',
  );
}
